language: r
cache: packages
dist: bionic
os:
- linux
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended
  texlive-fonts-extra
- tlmgr install standalone
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - ghostscript
      - gsfonts
notifications:
  slack:
    secure: YDWEobNljHKrq1H+Ejw2s1BX1KGnuI1tATejJ6STXITiStzXvh9OhuNi02yIB0wHI+JGkHMKgKk3SeBingDSzI9weL4ZadGJUO/L9lzfiRCGnzxm+tqchUZNOBX1aFnBi9Aek0ERQjYSgpml0ZdR9BQ2y98yQvb6+yxeefIePPKAon8ZB2npKOtkRGXJC5HNja8sizp3d4k/SEGd7g/J4Jz60F5UHjWzjtBzXTX1AKYUtFLBXj0BQH3uZvWSYHd+fCYqbj8HYtDcmOacFYoXsktSEYhpU1TBT9WB/O4i6VICm89Khfu3h18lFvFFgQA654rjBcNA+RNz9KLUg/4W5KaV2O91ialjgJ/Uy/X0IOEogjIG4ypKH2N/5/l0xHlRRJMYa9dcaPoXTrY0RXPNenDKAotClF/ue01GLa661fcX8LO8WlRSjEjg+zcil06QG9DIzpN8yFutoHFKXkDgdDmbf1niYsN46T28lcNvPelgBY0/tISM6hUGl2J4Jx3mBdmiHUXcRXvXHzS6PGw+CmQb5HqfTnop7+mJBr9sDowTKbBRSF09ge4keU7CFzXQZtUyOIzfh+BTS48BhcvnwH8P2hbzcnryeSBD06H1Y9oAsazGD/3deMDY4IDS1D3RFvouj2tr63KWYFGYcj6lWLoRbYZIOdVPGGhjI3zGeW8=
